### ISSUE TITLE
Autostart issues with Spotify

### ISSUE THREAD

**Issue by ghost** [anurag3301/my-dwm#2]
When examining your config.def.h, I noticed that spotify is supposed to start in the 8th tab.  But when spotify launches it in the current tab.  Does it auto start for you in the 8th or what. This entire problem is making me feel stupid.

Thanks!

**Comment by anurag3301** [comment]
On no, you are absolutely correct. Spotify does launch in the current tab. And yes Spotify is in autostart as you can see in my `my-linux-setup/config/xorg.xinitrc`.
The workaround is, as my system boots up and everything is in autostart is launched. Everything launches in their respective tabs except Spotify. All you have to do is restart DWM, and Spotify will be in correct tab. 
So as you start dwm just hit `mod+shift+q` aka `alt+shift+q` to restart Spotiy. I know an extra step but not sure why its happening with only spotify.

**Comment by anurag3301** [comment]
@boecker Try this and let me know if it works for you

**Comment by ghost** [comment]
yes this worked, thank you.  Is there any way I can permanently fix?

**Comment by anurag3301** [comment]
Not as of now, not sure who is the culprit, is it Spotify or dwm. I'll look into it.

**Comment by anurag3301** [comment]
@boecker LOL turns out its a pretty common problem:
[https://bbs.archlinux.org/viewtopic.php?id=254937](https://bbs.archlinux.org/viewtopic.php?id=254937)
[https://www.reddit.com/r/suckless/comments/im26qs/how_to_open_spotify_in_0th_monitor_9th_tag/](https://www.reddit.com/r/suckless/comments/im26qs/how_to_open_spotify_in_0th_monitor_9th_tag/)
[https://github.com/LukeSmithxyz/dwm/issues/49](https://github.com/LukeSmithxyz/dwm/issues/49)
now looking for some solutions

**Comment by ghost** [comment]
wow.  just wow

**Comment by ghost** [comment]
Hey, do you know how I can add you dwm build to a login manager?

**Comment by par4m** [comment]
> Hey, do you know how I can add you dwm build to a login manager?

`/usr/share/xsessions/dwm.desktop`:
```c
[Desktop Entry]
Encoding=UTF-8
Name=dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
```

**Comment by par4m** [comment]
@anurag3301 Were you able to find a fix for this ?

**Comment by anurag3301** [comment]
@par4m Nah man, I tried a few things like the above mentioned Reddit thread, but that didn't work for me, or I was doing something wrong. I didnt go deep to fix this, I just restart dwm with `mod+shift+q` when I start my system and form them everything is fine. I'll again try to fix it.

**Comment by anurag3301** [comment]
Hey @par4m I think I got it. I tried this workaround mentioned by this guy in the `spotifywm` issue
https://github.com/dasJ/spotifywm/issues/8#issuecomment-1114121742

Just add the following to your startup script, it will add a delay of 0.5 sec, but it works. If you want you can try reducing the delay
```sh
spotify &
sleep 0.5
xdotool set_window --classname Spotify --class spotify --name Spotify $(wmctrl -l | awk 'END{print $1}')
```
Try and let me know if it worked for you
I did following with my `xinitrc`
![image](https://user-images.githubusercontent.com/52702259/172000640-71fd58bf-6c60-499e-95e7-20792ccac07d.png)

**Comment by anurag3301** [comment]
Okay so delay of 0.5 sec didnt work for me, had to increase it. Just set to 1 sec and its working. Ill experiment around with other values. If it doesn't work for you try increasing the delay.

**Comment by par4m** [comment]
Ahh no luck, tried 0.5s to 10 but still it didn't work not sure why

**Comment by par4m** [comment]
Have you tried it with the swallow patch ? spotify could be passed to st and a title could be set im guessing

**Comment by anurag3301** [comment]
> Ahh no luck, tried 0.5s to 10 but still it didn't work not sure why

um you sure you did it correctly, you should be starting spotify before starting dwm, best start spotify first then the delay and the `xdotool` thing.

**Comment by anurag3301** [comment]
> Have you tried it with the swallow patch? spotify could be passed to st and a title could be set im guessing

Never tried the swallow patch but as far as I know, its used by the terminal to get swallowed when an application is run, like mpv. How can we use that to fix this issue.

**Comment by par4m** [comment]
oh my bad, was running it as a script. worked on startup, thought i'd rather not run it at startup. 
im guessing there's no workaround for running it manually.

I haven't tried the swallow patch either since it messes up my build for some reason but maybe spotify can be run with `st -e spotify -t title -c class`   and a window rule can be added depending on xwininfo.
see: https://git.suckless.org/st/file/st.1.html#l58
Though it'll all depend on how swallow sets window rules

**Comment by par4m** [comment]
[dynamicswallow](https://dwm.suckless.org/patches/dynamicswallow/) has an option for this
```
dwmswallow SWALLOWER [-c CLASS] [-i INSTANCE] [-t TITLE]
```

**Comment by anurag3301** [comment]
@par4m as your wish, Ill check this swallow patch, if you get it working do let me know.

**Comment by anurag3301** [comment]
Closing as the delay with xdotool works for me and there is no update on this. Hope Spotify fixes their client.
